spring.application.name=Spring_exception
spring.datasource.url=jdbc:postgresql://localhost:5433/exception
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver